// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygPGnyOqKNlfoOXwfSMlsdDKHd-kMjhY',
    appId: '1:207014988465:web:7134ed7f7875f7e7b3f090',
    messagingSenderId: '207014988465',
    projectId: 'bite-food-delivery-e3edf',
    authDomain: 'bite-food-delivery-e3edf.firebaseapp.com',
    storageBucket: 'bite-food-delivery-e3edf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6C7xbKXdEHgw1eMt34EqdYA42BC-slDo',
    appId: '1:207014988465:android:492e4765c8d62ff1b3f090',
    messagingSenderId: '207014988465',
    projectId: 'bite-food-delivery-e3edf',
    storageBucket: 'bite-food-delivery-e3edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpRDLF_ydUned-Jkd-osAr1CREgivsP0',
    appId: '1:207014988465:ios:a0dfd61f69a1ffb8b3f090',
    messagingSenderId: '207014988465',
    projectId: 'bite-food-delivery-e3edf',
    storageBucket: 'bite-food-delivery-e3edf.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpRDLF_ydUned-Jkd-osAr1CREgivsP0',
    appId: '1:207014988465:ios:a0dfd61f69a1ffb8b3f090',
    messagingSenderId: '207014988465',
    projectId: 'bite-food-delivery-e3edf',
    storageBucket: 'bite-food-delivery-e3edf.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBygPGnyOqKNlfoOXwfSMlsdDKHd-kMjhY',
    appId: '1:207014988465:web:ff7fe7c81d1326cfb3f090',
    messagingSenderId: '207014988465',
    projectId: 'bite-food-delivery-e3edf',
    authDomain: 'bite-food-delivery-e3edf.firebaseapp.com',
    storageBucket: 'bite-food-delivery-e3edf.firebasestorage.app',
  );
}
