// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJVKGZZiJk1i5e2UYGnJpswSY1R4VWKQ',
    appId: '1:460586379661:web:121c1fed32149dce8775c4',
    messagingSenderId: '460586379661',
    projectId: 'bite-food-delivery-9e368',
    authDomain: 'bite-food-delivery-9e368.firebaseapp.com',
    storageBucket: 'bite-food-delivery-9e368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Vn-9QDwFIrjI0aBjd81xRfi7G7N-rns',
    appId: '1:460586379661:android:b3aacaef90c2a7af8775c4',
    messagingSenderId: '460586379661',
    projectId: 'bite-food-delivery-9e368',
    storageBucket: 'bite-food-delivery-9e368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQceNpPpmpXLr0asTGPbfGHB0remZ4_GE',
    appId: '1:460586379661:ios:046693f4214b85188775c4',
    messagingSenderId: '460586379661',
    projectId: 'bite-food-delivery-9e368',
    storageBucket: 'bite-food-delivery-9e368.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQceNpPpmpXLr0asTGPbfGHB0remZ4_GE',
    appId: '1:460586379661:ios:046693f4214b85188775c4',
    messagingSenderId: '460586379661',
    projectId: 'bite-food-delivery-9e368',
    storageBucket: 'bite-food-delivery-9e368.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJVKGZZiJk1i5e2UYGnJpswSY1R4VWKQ',
    appId: '1:460586379661:web:e7becda99be413ec8775c4',
    messagingSenderId: '460586379661',
    projectId: 'bite-food-delivery-9e368',
    authDomain: 'bite-food-delivery-9e368.firebaseapp.com',
    storageBucket: 'bite-food-delivery-9e368.firebasestorage.app',
  );

}