// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGh2SG8NbDMhWEtuHNLDRrMK7I6tlSceA',
    appId: '1:579293461649:web:f83fa535591663a1f1d330',
    messagingSenderId: '579293461649',
    projectId: 'bite-food-delivery-11be9',
    authDomain: 'bite-food-delivery-11be9.firebaseapp.com',
    storageBucket: 'bite-food-delivery-11be9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskZ81CnJ1Ne4t4IXIIjIooZsGMJtQb6M',
    appId: '1:579293461649:android:432ae11a0d1b1132f1d330',
    messagingSenderId: '579293461649',
    projectId: 'bite-food-delivery-11be9',
    storageBucket: 'bite-food-delivery-11be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WoALVAky9zOUHqK-_Kt1hmZ5dMJiN1s',
    appId: '1:579293461649:ios:339828399f9b7f65f1d330',
    messagingSenderId: '579293461649',
    projectId: 'bite-food-delivery-11be9',
    storageBucket: 'bite-food-delivery-11be9.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3WoALVAky9zOUHqK-_Kt1hmZ5dMJiN1s',
    appId: '1:579293461649:ios:339828399f9b7f65f1d330',
    messagingSenderId: '579293461649',
    projectId: 'bite-food-delivery-11be9',
    storageBucket: 'bite-food-delivery-11be9.firebasestorage.app',
    iosBundleId: 'com.example.bite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGh2SG8NbDMhWEtuHNLDRrMK7I6tlSceA',
    appId: '1:579293461649:web:bdd1a29dab1ec256f1d330',
    messagingSenderId: '579293461649',
    projectId: 'bite-food-delivery-11be9',
    authDomain: 'bite-food-delivery-11be9.firebaseapp.com',
    storageBucket: 'bite-food-delivery-11be9.firebasestorage.app',
  );

}